spring:
  profiles:
    active: development
  mail:
    host: smtp.gmail.com
    username: spoko.slack@gmail.com
    password: Staszek@Programista97
    port: 587
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          auth: true
          starttls.enable: true
    debug: true