spring:
  h2:
    console:
      enabled: false
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
server:
  port: 8081
fe_url: http://localhost:4201
be_url: http://localhost:8081